# This is a trigger workflow to trigger the Fish-Blog-Deploy action in [Fish-Blog repo](https://github.com/YK-Unit/Fish-Blog)

name: Fish-Blog-Deploy-Trigger

runs:
  using: 'node20'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: ["README.md", "LICENSE.md", ".gitignore", "template/**"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
    # from: https://github.com/marketplace/actions/repository-dispatch
    - name: Trigger the Fish-Blog-Deploy action
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.Blog_Workflow_PAT }}
        repository: YK-Unit/Fish-Blog
        event-type: deploy-blog-event
